postgresql_databases:
  - name: sonarqube_db
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    state: present

  - name: artifactory_db
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    state: present

postgresql_users:
  - name: sonarqube_user
    password: sonar-password
    db: sonarqube_db
    priv: "ALL"
    state: present

  - name: artifactory_user
    password: artifactory-password
    db: artifactory_db
    priv: "ALL"
    state: present