nfs:
  hosts:
    172.31.40.51:
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/iPhone.pem


webservers:
  hosts:
    172.31.23.94:
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/iPhone.pem
    172.31.17.103:
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/iPhone.pem
    172.31.21.54:
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/iPhone.pem

db:
  hosts:
    172.31.26.114:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/iPhone.pem

lb:
  hosts:
    172.31.18.41:
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/iPhone.pem