- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: true
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
    
- name: update LB server
  hosts: lb
  become: true
  tasks:
    - name: Update apt repo
      apt:
        update_cache: true

  - name: Ensure Wireshark is at the latest version
    hosts: all
    become: yes
    tasks:
      - name: Ensure Wireshark is at the latest version
        package:
          name: wireshark
          state: latest

            