---

- hosts: all

  tasks:

    - name: include dynamic variables

      import_playbook:

        name: ../static-assignments/common.yml

      block:

        - include_vars: ../dynamic-assignments/env-vars.yml

  tags:

    - always


- hosts: uat-webservers

  tasks:
    - name: set up uat webservers
      block:
        - import_vars: ../static-assignments/uat-webservers.yml
